[package]
name = "splicer"
version = "0.1.0"
edition = "2021"

[[bin]]
doc = false
name = "splicer"
path = "src/main.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"  # or serde_toml if you prefer TOML
anyhow = { workspace = true }
wat = { workspace = true }
wirm = { workspace = true }
clap = { workspace = true }
