[package]
name = "splicer"
version = "1.0.0"
edition = "2021"
authors = ["Elizabeth Gilbert"]
description = "Plan and generate middleware splice operations for WebAssembly component composition graphs."
license = "Apache-2.0"

readme = "README.md"
repository = "https://github.com/ejrgilbert/splicer"
categories = ["wasm"]
keywords = ["wasm", "WebAssembly", "components", "composition"]

[[bin]]
doc = false
name = "splicer"
path = "src/main.rs"

[dependencies]
cviz = { version = "1.0.1" }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"  # or serde_toml if you prefer TOML
anyhow = "1.0.86"
clap = { version = "4.5.58", features = ["derive"] }
wasmparser = "0.245.1"
